[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3-pip", "ffmpeg"]
aptPkgs = []

[phases.install]
cmds = [
  "pip3 install --upgrade 'yt-dlp[default]'",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
