[phases.setup]
aptPkgs = ["python3", "python3-pip", "ffmpeg"]

[phases.install]
cmds = [
  "pip3 install yt-dlp",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
